# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  yashpuri.me:
    site_hosts:
      - canonical: tech-support.test
        # redirects:
        #   - www.tech-support.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: purigr8@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
